# Site settings
name: Slim Pickins Jekyll Theme
email: 
author: Chrisanthropic

keywords: jekyll, jekyll theme, jekyll framework, stuffthings
description: > # this means to ignore newlines until "baseurl:"
  Witty description here.

baseurl: /slim-pickins-jekyll-theme
url: https://chrisanthropic.github.io

header: yes
header_sm: images/banner-small.jpg
header_med: images/banner-med.jpg
header_large: images/banner-large.jpg
header_xl: images/banner-xl.jpg


# Exclude our ruby stuff
exclude: [.bundle, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, .last_optimized]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

destination: _site

gems:
  - jekyll-feed

feed:
  path: atom.xml
  
# Compress our Css
#sass:
#    style: :compressed

permalink: /blog/:year/:title

#### SEO Stuff
# Google Analytics
google_universal_analytics: 
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                      #enter your App ID
facebook_locale: en_US
facebook_page:                        #the URL of your Facebook Page
facebook_image:                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user: 
twitter_card: true
twitter_image:                        #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
